const FORM_TEMP = '<div class="basic-grey">'
+'<form action="" method="/" class="STYLE-NAME">'
+'<h1>属性值'
+'<span></span>'
+' </h1>'
+'<label>'
+'<span>dom_id :</span>'
+'<input id="wtc_dom_id" readonly type="text" placeholder="dom_id" />'
+'</label>'
+'<label>'
+'<span title="填写父级ID,层级关系">parent_id :</span>'
+'<input id="wtc_parent_id" type="text" placeholder="父级id" />'
+'</label>'
+'<label>'
+'<span title="模块排列顺序">sort :</span>'
+'<input id="wtc_rank_num" type="text" placeholder="排列顺序" />'
+'</label>'
+'<label>'
+'<span title="类名">class_name :</span>'
+'<input id="wtc_class_name" type="text" placeholder="类名" />'
+'</label>'
+'<label>'
+'<span title="样式(分号;隔开)">style :</span>'
+'<textarea id="wtc_style_content" placeholder="示例： display:none;"></textarea>'
+'</label>'
+'<label style="display: none;">'
+'<span>Subject :</span>'
+'<select name="selection">'
+'<option value="Job Inquiry">Job Inquiry</option>'
+'<option value="General Question">General Question</option>'
+'</select>'
+'</label>'
+'<label>'
+'<span>&nbsp;</span>'
+'<input id="wtc_save_form_btn" type="button" class="button" value="保存" />'
+'</label>'
+'</form>'
+'</div>'